# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rwithings}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marshall Huss"]
  s.date = %q{2010-01-26}
  s.description = %q{Ruby library for the Withings WiFi scale API}
  s.email = %q{mwhuss@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/rwithings.rb",
     "lib/rwithings/rwithings.rb",
     "lib/rwithings/rwithings/base.rb",
     "lib/rwithings/rwithings/errors.rb",
     "lib/rwithings/rwithings/user.rb",
     "rwithings.gemspec",
     "test/helper.rb",
     "test/json_responses/getbyuserid.json",
     "test/rwithings/test_base.rb",
     "test/rwithings/test_user.rb"
  ]
  s.homepage = %q{http://github.com/mwhuss/rwithings}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby library for the Withings WiFi scale API}
  s.test_files = [
    "test/helper.rb",
     "test/rwithings/test_base.rb",
     "test/rwithings/test_user.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

